# Generated by Django 4.2 on 2023-08-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mingleapp', '0002_customuser_profile_picture_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
