# Generated by Django 4.2 on 2023-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mingleapp', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
